version: '3'
services:
  db:
    container_name: phpmyadmin-db
    image: mysql
    volumes:
      - "$PWD/data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: database1
    networks:
      - net
  admin:
    container_name: phpmyadmin-web
    image: phpmyadmin/phpmyadmin
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306      
    networks:
      - net
networks:
  net:
